### ISSUE TITLE
Notifications very slow to arrive

### ISSUE THREAD

**Issue by Grandpa-G** [anxuae/pycups-notify#2]
I am doing a simple print through cups in python3 on a Raspberry Pi. I do a very simple setup
`        # Create a new subscriber
        self.printerName = 'DYMO-LabelWriter-450'
        cups.setUser(self.printerName)

        self.sub = Subscriber(self.conn)
        # Subscribe the callback
        self.sub.subscribe(self.my_callback)#, [event.CUPS_EVT_JOB_CREATED])
`
and then start the print job. The printer is a DYMO label printer.

`             self.printId = self.conn.printFile(self.printerName, self.printFile, "Label", options)
`

The printer is completely done before I get any events and then they progress events with percentages start coming. They are at least several minutes behind the completion of the printing. Each progress comes about 10 or more seconds apart.

Any suggestions how to get it to respond in real time with what the printer is doing?

**Comment by anxuae** [comment]
Hello @Grandpa-G 

Can you check on the CUPS web interface (go to http://127.0.0.1:631/jobs on your raspberrypi) and check if the job status is correctly updated in real time? If not, that means that the issue is coming from the printer.

anxuae

**Comment by anxuae** [comment]
No news since long time. Please re-open if issue occurs again
